# Shipyard CLI - golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
    - contract

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Official Go static analyzer
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Go static analysis tool

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - (*os.File).Close
      - (io.ReadCloser).Close
      - os.Remove
      - (*github.com/gofrs/flock.Flock).Unlock

  govet:
    disable:
      - shadow
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable - needed for editor integration
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - errcheck
    - path: test/
      linters:
        - gocyclo
        - gosec
        - errcheck

    # Ignore long lines in tests
    - path: _test\.go
      linters:
        - lll

    # Allow unchecked errors in specific safe cases
    - text: "Error return value of `.*RegisterFlagCompletionFunc` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*GetBool` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*Help` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*SetSCC` is not checked"
      linters:
        - errcheck

    # Allow type assertions in prompt package (bubbletea models)
    - path: internal/prompt/
      text: "Error return value is not checked"
      linters:
        - errcheck

    # Ignore staticcheck SA1019 (deprecated) for known cases
    - text: "SA1019.*strings.Title"
      linters:
        - staticcheck

    # Ignore gosec G104 (unhandled errors) for cleanup operations
    - text: "G104.*os.Remove"
      linters:
        - gosec
    - text: "G104.*cmd.Help"
      linters:
        - gosec

    # Ignore gosec file permissions warnings
    - text: "G301|G306"
      linters:
        - gosec

    # Ignore gosec file inclusion warnings (false positives)
    - text: "G304"
      linters:
        - gosec

