# Shipyard CLI - golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: false # Don't run linters on test files
  build-tags:
    - integration
    - contract

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck # Check for unchecked errors
    - govet # Official Go static analyzer
    - ineffassign # Detect ineffective assignments
    - staticcheck # Go static analysis tool
    - unused # Check for unused code

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - (*os.File).Close
      - (io.ReadCloser).Close
      - os.Remove
      - os.RemoveAll
      - os.Rename
      - os.Setenv
      - os.Unsetenv
      - os.Chdir
      - os.WriteFile
      - (*github.com/gofrs/flock.Flock).Unlock
      - (io.WriteCloser).Close
      - (*os/exec.Cmd).Run
      - (*os/exec.Cmd).Execute
      - (io.Writer).Write
      - (*encoding/json.Encoder).Encode
      - (*net/http.Response).Body.Close

  govet:
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G204 # Subprocess launched with variable - needed for editor integration

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude test files from all linters
  exclude-dirs:
    - test

  exclude-files:
    - ".*_test\\.go$"

  # Exclude some linters from running on tests files
  exclude-rules:
    # Allow unchecked errors in specific safe cases
    - text: "Error return value of `.*RegisterFlagCompletionFunc` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*GetBool` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*Help` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*SetSCC` is not checked"
      linters:
        - errcheck

    # Allow type assertions in prompt package (bubbletea models)
    - path: internal/prompt/
      text: "Error return value is not checked"
      linters:
        - errcheck

    # Ignore staticcheck SA1019 (deprecated) for known cases
    - text: "SA1019.*strings.Title"
      linters:
        - staticcheck

    # Ignore gosec G104 (unhandled errors) for cleanup operations
    - text: "G104.*os.Remove"
      linters:
        - gosec
    - text: "G104.*cmd.Help"
      linters:
        - gosec

    # Ignore gosec file permissions warnings
    - text: "G301|G306"
      linters:
        - gosec

    # Ignore gosec file inclusion warnings (false positives)
    - text: "G304"
      linters:
        - gosec
