# Shipyard CLI - golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
    - contract

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Official Go static analyzer
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Go static analysis tool
    - unused        # Detect unused constants, variables, functions
    - gofmt         # Check formatting
    - goimports     # Check import order
    - misspell      # Check spelling
    - gocritic      # Comprehensive Go source code linter
    - gocyclo       # Check cyclomatic complexity
    - gosec         # Security issues
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - stylecheck    # Style checks
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Detect unused function parameters
    - prealloc      # Find slice declarations that could be preallocated

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    shadow: true
  
  gocyclo:
    min-complexity: 15
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable - needed for editor integration
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - errcheck
    - path: test/
      linters:
        - gocyclo
        - gosec
        - errcheck
    
    # Ignore long lines in tests
    - path: _test\.go
      linters:
        - lll

