version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: shipyard
    main: ./cmd/shipyard
    binary: shipyard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: shipyard
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CONTRIBUTING*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  # Disable GoReleaser's changelog - Shipyard generates its own via 'shipyard release-notes'
  disable: true

brews:
  - name: shipyard
    ids:
      - shipyard
    repository:
      owner: natonathan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/NatoNathan/shipyard"
    description: "CLI tool for managing project deliverables and generating changelogs"
    license: "MIT"
    install: |
      bin.install "shipyard"

      # Generate and install shell completions
      output = Utils.safe_popen_read("#{bin}/shipyard", "completion", "bash")
      (bash_completion/"shipyard").write output

      output = Utils.safe_popen_read("#{bin}/shipyard", "completion", "zsh")
      (zsh_completion/"_shipyard").write output

      output = Utils.safe_popen_read("#{bin}/shipyard", "completion", "fish")
      (fish_completion/"shipyard.fish").write output
    test: |
      system "#{bin}/shipyard", "--version"

release:
  github:
    owner: natonathan
    name: shipyard
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  # Release notes will be generated by Shipyard itself and updated by the workflow
  # Draft release will be published after shipyard generates the proper notes
